app:
  name: FROSTGROVE_VV_TEMPLATE

transports:
  fiber:
    port: 8000
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
    prefork: false

infra:
  db:
    engine: postgres
    driver: pgx
    host: localhost
    port: 5432
    user: app
    password: secret
    name: app
    sslmode: disable
    params:
      timezone: UTC

    migration:
      path: resources/migrations

clients:
  # put external service configs here (e.g. payment_api, notification_api)

internal:
  # put configs for internal microservices/modules here

observability:
  logger:
    name: "app-logger"
